In [1]:
import getpass
import pandas as pd
import numpy as np
import mysql.connector

---------------------
CONEXÃO COM O SERVIDOR MYSQL
---------------------

In [2]:
pword=getpass.getpass()

········

In [3]:
cnx = mysql.connector.connect(user='root', password=pword,
                              host='127.0.0.1',
                              database='anvisa')
cursor = cnx.cursor()

In [4]:
df_opr= pd.read_sql("SELECT * from laboratorio", cnx)
df_opr.head(3)

                 cnpj                                               nome
0  00.029.372/0001-40  GE HEALTHCARE DO BRASIL COMÉRCIO E SERVIÇOS PA...
1  00.317.372/0001-46                               GALDERMA BRASIL LTDA
2  00.376.959/0001-26  IFAL INDUSTRIA E COMERCIO DE PRODUTOS FARMAC LTDA

---------------------
TABELA EXTERNA - DADOS.GOV.BR - ANVISA
---------------------
https://dados.gov.br/dataset/preco-de-medicamentos-no-brasil-consumidor

In [5]:
csv_drugs = './TA_PRECO_MEDICAMENTO.csv'

In [6]:
data=pd.read_csv(csv_drugs, sep=';', index_col=False)

c:\users\f1693478\appdata\local\programs\python\python37-32\lib\site-packages\IPython\core\interactiveshell.py:3166: DtypeWarning: Columns (36) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [15]:
df_med=data.rename(columns={'SUBSTÂNCIA':'PRINC_ATIVO'})
df_med=df_med.rename(columns={'LABORATÓRIO':'LAB'})
df_med=df_med.rename(columns={'REGIME DE PREÇO':'REG_PRECO'})
df_med=df_med.rename(columns={'APRESENTAÇÃO':'APRESENTACAO'})
df_med=df_med.rename(columns={'CLASSE TERAPÊUTICA':'CLAS_TERAPEUTICA'})
df_med=df_med.rename(columns={'TIPO DE PRODUTO (STATUS DO PRODUTO)':'TIP_PRODUTO'})
df_med=df_med.rename(columns={'RESTRIÇÃO HOSPITALAR':'RESTR_HOSP'})
df_med=df_med.rename(columns={'CÓDIGO GGREM':'CD_GGEREM'})
df_med=df_med.rename(columns={'ANÁLISE RECURSAL':'ANL_RECURSAL'})
df_med=df_med.rename(columns={'LISTA DE CONCESSÃO DE CRÉDITO TRIBUTÁRIO (PIS/COFINS)':'LS_PIS_COFINS'})
df_med=df_med.rename(columns={'COMERCIALIZAÇÃO 2019':'COMERC_2019'})
df_med=df_med.rename(columns={'EAN 1':'EAN_1'})
df_med=df_med.rename(columns={'EAN 2':'EAN_2'})
df_med=df_med.rename(columns={'EAN 3':'EAN_3'})
df_med=df_med.rename(columns={'PMC 20%':'PMC'})
df_med=df_med.rename(columns={'PF 20%':'PF'})
df_med.head(1)

,PRINC_ATIVO,CNPJ,LAB,CD_GGEREM,REGISTRO,EAN_1,EAN_2,EAN_3,PRODUTO,APRESENTACAO,...,PMC 18% ALC,PMC,RESTR_HOSP,CAP,CONFAZ 87,ICMS 0%,ANL_RECURSAL,LS_PIS_COFINS,COMERC_2019,TARJA
0,ACETATO DE LANREOTIDA,07.718.721/0001-80,BEAUFOUR IPSEN FARMACÊUTICA LTDA,539220120001407,1697700020094,7898932171249,7898932171218,-,SOMATULINE AUTOGEL,120 MG SOL INJ LIB PROL CT ENV AL/PLAS SER PRE...,...,"4141,17","4244,70",Não,Sim,Sim,Não,(7),Positiva,Não,Tarja -(*)

In [16]:
df_med.columns

Index(['PRINC_ATIVO', 'CNPJ', 'LAB', 'CD_GGEREM', 'REGISTRO', 'EAN_1', 'EAN_2',
       'EAN_3', 'PRODUTO', 'APRESENTACAO', 'CLAS_TERAPEUTICA', 'TIP_PRODUTO',
       'REG_PRECO', 'PF Sem Impostos', 'PF 0%', 'PF 12%', 'PF 17%',
       'PF 17% ALC', 'PF 17,5%', 'PF 17,5% ALC', 'PF 18%', 'PF 18% ALC', 'PF',
       'PMC 0%', 'PMC 12%', 'PMC 17%', 'PMC 17% ALC', 'PMC 17,5%',
       'PMC 17,5% ALC', 'PMC 18%', 'PMC 18% ALC', 'PMC', 'RESTR_HOSP', 'CAP',
       'CONFAZ 87', 'ICMS 0%', 'ANL_RECURSAL', 'LS_PIS_COFINS', 'COMERC_2019',
       'TARJA'],
      dtype='object')

In [17]:
df_med_f=df_med[['CNPJ','LAB','PRINC_ATIVO','PRODUTO','APRESENTACAO','TIP_PRODUTO','TARJA','EAN_1','EAN_2','EAN_3','LS_PIS_COFINS','PF','PMC', 'REGISTRO','CD_GGEREM']]
# df_med[df_med['CNPJ']=='07.718.721/0001-80']

In [10]:
df_med_f.head(3)

,CNPJ,LAB,PRINC_ATIVO,PRODUTO,APRESENTACAO,TIP_PRODUTO,TARJA,EAN_1,EAN_2,LS_PIS_COFINS,PF,PMC,REGISTRO,CD_GGEREM
0,07.718.721/0001-80,BEAUFOUR IPSEN FARMACÊUTICA LTDA,ACETATO DE LANREOTIDA,SOMATULINE AUTOGEL,120 MG SOL INJ LIB PROL CT ENV AL/PLAS SER PRE...,Novo,Tarja -(*),7898932171249,7898932171218,Positiva,"3070,44","4244,70",1697700020094,539220120001407
1,45.992.062/0001-65,GERMED FARMACEUTICA LTDA,ACICLOVIR,ACICLOVIR,400 MG COM CT BL AL PLAS PVDC OPC X 20,Genérico,Tarja Vermelha(*),7896004708362,-,Positiva,"72,11","99,69",1058309640048,526120110126207
2,45.992.062/0001-65,GERMED FARMACEUTICA LTDA,ACICLOVIR,ACICLOVIR,400 MG COM CT BL AL PLAS PVDC OPC X 30,Genérico,Tarja Vermelha(*),7896004708379,-,Positiva,"108,18","149,55",1058309640056,526120110126307

In [ ]:
#CARGA TABELA LABORATORIO
lab = df_med_f[['CNPJ','LAB']]
lab = lab.drop_duplicates()
df_lab =lab.astype(object).where(pd.notnull(lab), None)
for row in df_lab.itertuples():
#     cnpj0= ''.join(c for c in row.CNPJ if c not in '/.-')
    sql = "INSERT INTO laboratorio (cnpj, nome)  VALUES (%s, %s)"
    val = (row.CNPJ, (row.LAB))
    try:
        cursor.execute(sql, val)
    except:
        raise
cnx.commit()
sql_lab= pd.read_sql("SELECT * from laboratorio", cnx)
sql_lab.head(3)

In [ ]:
# registro = df_med_f[['EAN_1']]
# registro = registro.drop_duplicates()
# registro

In [ ]:
#CARGA TABELA REGISTRO
registro = df_med_f[['CD_GGEREM', 'REGISTRO']]
registro = registro.drop_duplicates()
df_registro =registro.astype(object).where(pd.notnull(registro), None)
df_registro = df_registro.replace(to_replace='    -     ', value=0)

for row in df_registro.itertuples():
    print(row)
    sql = "INSERT INTO registro (idRegistro, CD_GGEREM)  VALUES (%s, %s)"
    val = (row.REGISTRO ,row.CD_GGEREM)
    try:
        cursor.execute(sql, val)
    except:
        raise
cnx.commit()
sql_lab= pd.read_sql("SELECT * from registro", cnx)
sql_lab.head(3)

In [31]:
sql = "DELETE FROM preco"
cursor.execute(sql)

In [13]:
#CARGA TABELA MEDICAMENTO
medicam = df_med_f[['PRINC_ATIVO','PRODUTO','APRESENTACAO','TIP_PRODUTO', 'TARJA', 'CD_GGEREM']]
medicam = medicam.drop_duplicates()
df_medicam =medicam.astype(object).where(pd.notnull(medicam), None)
        
for row in df_medicam.itertuples():
    
    print(row)
    principio=str(row.PRINC_ATIVO)[0:300]
    apresentacao=str(row.APRESENTACAO)[0:150]
    sql = "INSERT INTO medicamento (principio_ativo, apresentacao, produto, tarja, tipo_produto, Registro_CD_GGEREM)  VALUES (%s, %s, %s, %s, %s, %s)"
    val = (principio ,apresentacao ,row.PRODUTO ,row.TARJA ,row.TIP_PRODUTO,  row.CD_GGEREM)
    try:
        cursor.execute(sql, val)
    except:
        raise
cnx.commit()
sql_lab= pd.read_sql("SELECT * from medicamento", cnx)
sql_lab.head(3)

,principio_ativo,apresentacao,produto,tarja,tipo_produto,Registro_CD_GGEREM
0,21-ACETATO DE DEXAMETASONA;CLOTRIMAZOL,"10 MG/G + 0,443 MG/G CREM DERM CT BG AL X 40 G",BAYCUTEN N,Tarja Venda Livre/Sem Tarja (*),Novo,538912020009303
1,ABACAVIR;ISOCONAZOL;NITRATO DE ISOCONAZOL,APRESENTAÇÃO 01&nbsp;02,PRODUTO DE MEDICAMENTO PARA TESTE,Tarja Vermelha(*),Genérico,542313030000003
2,ABATACEPTE,125 MG/ML SOL INJ SC CT 4 SER PREENC VD TRANS ...,ORENCIA,Tarja Vermelha(*),Biológico,505113100020505

In [33]:
#CARGA TABELA PRECO
preco = df_med_f[['EAN_1','EAN_2','EAN_3','LS_PIS_COFINS', 'PF', 'PMC', 'PRINC_ATIVO', 'APRESENTACAO', 'CD_GGEREM', 'PRODUTO']]
preco = preco.drop_duplicates()
df_preco =preco.astype(object).where(pd.notnull(preco), None)
df_preco = df_preco.replace(to_replace='    -     ', value=0)
# df_preco      

for row in df_preco.itertuples():
    
    print(row)
    if row.PF is None:
        pf0=0
    else:
        pf0=(row.PF).replace(',', '.')
    pf=float(pf0)
    if row.PMC is None:
        pmc0=0
    else:
        pmc0=(row.PMC).replace(',', '.')
    pmc=float(pmc0)
    principio=str(row.PRINC_ATIVO)[0:300]
    apresentacao=str(row.APRESENTACAO)[0:150]
    sql = "INSERT INTO preco (ean_1, ean_2, ean_3, ls_pis_cofins, pf, pmc, Medicamento_principio_ativo, Medicamento_apresentacao, Medicamento_Registro_CD_GGEREM, Medicamento_produto)  VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
    val = (row.EAN_1, row.EAN_2, row.EAN_3, row.LS_PIS_COFINS, pf, pmc,  principio ,apresentacao ,row.CD_GGEREM, row.PRODUTO)
    try:
        cursor.execute(sql, val)
    except:
        raise
cnx.commit()
sql_lab= pd.read_sql("SELECT * from preco", cnx)
sql_lab.head(3)

,ean_1,ean_2,ean_3,ls_pis_cofins,pf,pmc,Medicamento_principio_ativo,Medicamento_apresentacao,Medicamento_Registro_CD_GGEREM,Medicamento_produto
0,0,1896714215419,0,Negativa,20.80,27.69,CLIOQUINOL;SULFATO DE GENTAMICINA;TOLNAFTATO;V...,"0,5 MG/G + 1 MG/G + 10 MG/G + 10 MG/G POM DERM...",519024901167117,VALERATO DE BETAMETASONA/ SULFATO DE GENTAMICI...
1,0,1896714220505,0,Negativa,47.45,63.16,TINIDAZOL;TIOCONAZOL,20 MG/G + 30 MG/G CREM VAG CT BG PLAS OPC X 35...,504616020035517,VULNAGEN
2,0,1898328480092,0,Positiva,5438.18,7517.96,IMIGLUCERASE,400 U PÓ LIOF INJ CT FA VD INC,524000702152314,CEREZYME

In [36]:
#CARGA TABELA RELACAO LABORATORIO X MEDICAMENTO
relac = df_med_f[['CNPJ','PRINC_ATIVO','APRESENTACAO','CD_GGEREM', 'PRODUTO']]
relac = relac.drop_duplicates()
df_relac =relac.astype(object).where(pd.notnull(relac), None)
df_relac = df_relac.replace(to_replace='    -     ', value=0)

for row in df_relac.itertuples():
    
    print(row)
    principio=str(row.PRINC_ATIVO)[0:300]
    apresentacao=str(row.APRESENTACAO)[0:150]
    principio=str(row.PRINC_ATIVO)[0:300]
    apresentacao=str(row.APRESENTACAO)[0:150]
    sql = "INSERT INTO laboratorio_has_medicamento (Laboratorio_cnpj, Medicamento_principio_ativo, Medicamento_apresentacao, Medicamento_Registro_CD_GGEREM, Medicamento_produto)  VALUES (%s, %s, %s, %s, %s)"
    val = (row.CNPJ, principio, apresentacao, row.CD_GGEREM, row.PRODUTO)
    try:
        cursor.execute(sql, val)
    except:
        raise
cnx.commit()
sql_lab= pd.read_sql("SELECT * from laboratorio_has_medicamento", cnx)
sql_lab.head(3)

,Laboratorio_cnpj,Medicamento_principio_ativo,Medicamento_apresentacao,Medicamento_Registro_CD_GGEREM,Medicamento_produto
0,00.029.372/0001-40,GADODIAMIDA,287 MG / ML SOL INJ CT FA VD INC X 20 ML,541613060002104,OMNISCAN
1,00.029.372/0001-40,GADODIAMIDA,287 MG / ML SOL INJ CT FA VD INC X 10 ML,541613060002004,OMNISCAN
2,00.029.372/0001-40,GADODIAMIDA,287 MG / ML SOL INJ CT FA VD INC X 15 ML,541613060001904,OMNISCAN

In [ ]:
cnx.close()